name: Closed Pull Request

on:
  pull_request_target:
    types: ["closed"]

jobs:
  CreateCardForStandalonePR_job:
    name: Create release notes card
    runs-on: ubuntu-latest
    #permissions:
    #  repository-projects: write
    #permissions: write-all
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # PRs from forks don't have required token authorization
    # Dependabot works directly under our repository, but doesn't have enough priviledges to create project card



    # && github.event.author.type != 'Bot'
    # FIXME: REASON
    if: |
        github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateNote@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 11924207
          note: Lorem ipsum

  LogPayload_job:
    name: Log payload
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/LogPayload@v1