name: Closed Pull Request

on:
  # pull_request_target runs the fork code in our context. Do not use it elsewhere.
  # Here, it is OK because we're merging external PR and we're 100% sure about its content.
  pull_request_target:
    types: ["closed"]

jobs:
  CreateCardForStandalonePR_job:
    name: Create release notes card
    runs-on: ubuntu-latest
    permissions:
      # Limit available permissions to a required minimum, because we run under pull_request_target
      repository-projects: write
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    # && github.event.author.type != 'Bot'
    # FIXME: REASON
    if: |
        github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateNote@Pavel/Dev
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 11924207
          note: Lorem ipsum

  LogPayload_job:
    name: Log payload
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/LogPayload@v1